name: Linters

on: pull_request

env:
  GITHUB_BASE_REF: ${{ github.base_ref }}

jobs:
  run-linters:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Coder and Codesniffer
        run: composer global require drupal/coder dealerdirect/phpcodesniffer-composer-installer &&
          ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer

      - name: Fetch target branch
        run: git fetch -n origin ${GITHUB_BASE_REF}

      - name: Run phpcs
        run: git diff --diff-filter=d  origin/${GITHUB_BASE_REF} --name-only -- '*.php' '*.module' '*.inc' '*.install' '*.theme' ':!*.features.*' | xargs -r ~/.composer/vendor/bin/phpcs --standard=phpcs.xml
