name: Linters

on: pull_request

env:
  GITHUB_BASE_REF: ${{ github.base_ref }}

jobs:
  run-linters:

    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2

      - name: Install phpcs
        run: cd bin && ./install-php-linter

      - name: Fetch target branch
        run: git fetch -n origin ${GITHUB_BASE_REF}

      - name: Run phpcs with Drupal coding standards
        run: git diff --diff-filter=d  origin/${GITHUB_BASE_REF} --name-only -- '*.php' '*.module' '*.inc' '*.install' '*.theme' ':!*.features.*' | xargs -r ./bin/drupal/coder/vendor/bin/phpcs --standard=phpcs.xml
